#Upgrades
GumPower = "Bubble Gum Power"
SoapPower = "Soap Bubble Power"
#SpringPower = "Spring Power"
PoundPower = "Ground Pound Power"
HelmetPower = "Helmet Power"
# UmbrellaPower = "Umbrella Power"
ShockwavePower = "Shockwave Power"
BootsPower = "Boots Powerup"
PlungerPower = "Plungers Power"
#SlipperPower = "Slippers Power"
#LampshadePower = "Lampshade Power"
#BlackknightPower = "Black Knight Power"
ShovelPower = "Shovel Power"
ProgressiveJump = "Progressive Jump Upgrade"
ProgressiveSneak = "Progressive Sneak Upgrade"

Upgrades = "Upgrades"

#Ammo Upgrades
GumAmmoUpgrade = "Max Gum Ammo"
SoapAmmoUpgrade = "Max Soap Ammo"

#Monster Tokens
MT_BLACKKNIGHT = "Monster Token: Black Knight"
MT_MOODY = "Monster Token: Capt. Moody"
MT_CAVEMAN = "Monster Token: Caveman"
MT_CREEPER = "Monster Token: Creeper"
MT_GARGOYLE = "Monster Token: Gargoyle"
MT_GERONIMO = "Monster Token: Geronimo"
MT_GHOST = "Monster Token: Ghost"
MT_GHOSTDIVER = "Monster Token: Ghost Diver"
MT_GREENGHOST = "Monster Token: Green Ghost"
MT_HEADLESS = "Monster Token: Headless Spectre"
MT_MASTERMIND = "Monster Token: Mastermind"
MT_ROBOT = "Monster Token: Robot"
MT_REDBEARD = "Monster Token: Redbeard"
MT_SCARECROW = "Monster Token: Scarecrow"
MT_SEACREATURE = "Monster Token: Sea Creature"
MT_SPACEKOOK = "Monster Token: Space Kook"
MT_TARMONSTER = "Monster Token: Tar Monster"
MT_WITCH = "Monster Token: Witch"
MT_WITCHDOC = "Monster Token: Witchdoctor"
MT_WOLFMAN = "Monster Token: Wolfman"
MT_ZOMBIE = "Monster Token: Zombie"

MonsterTokens = "Monster Tokens"

#Keys
Clamor1_Key    = "Clamor 1 Key"
Hedge_Key      = "Hedge Maze Key"
Fishing_Key    = "Fishing Village Key"
Cellar2_Key    = "Cellar 2 Key"
Cellar3_Key    = "Cellar 3 Key"
Cavein_Key     = "Cave-in Key"
FishyClues_Key = "Fishy Clues Key"
Graveplot_Key  = "Graveplot Key"
Tomb1_Key      = "Tomb 1 Key"
Tomb3_Key      = "Tomb 3 Key"
Clamor4_Key    = "Clamor 4 Key"
MYM_Key        = "Mind Your Manors Key"
Coast_Key      = "Coast Key"
Attic_Key      = "Attic Key"
Knight_Key     = "Knight Key"
Creepy2_Key    = "Creepy 2 Key"
Creepy3_Key    = "Creepy 3 Key"
Gusts1_Key     = "Gusts 1 Key"
Gusts2_Key     = "Gusts 2 Key"
DLD_Key        = "Don't Look Down Key"
Shiver_Key     = "Shiver Key"

#Keys
Clamor1_KeyRing    = "Clamor 1 Key Ring"
Hedge_KeyRing      = "Hedge Maze Key Ring"
Fishing_KeyRing    = "Fishing Village Key Ring"
Cellar2_KeyRing    = "Cellar 2 Key Ring"
Cellar3_KeyRing    = "Cellar 3 Key Ring"
Cavein_KeyRing     = "Cave-in Key Ring"
FishyClues_KeyRing = "Fishy Clues Key Ring"
Graveplot_KeyRing  = "Graveplot Key Ring"
Tomb1_KeyRing      = "Tomb 1 Key Ring"
Tomb3_KeyRing      = "Tomb 3 Key Ring"
Clamor4_KeyRing    = "Clamor 4 Key Ring"
MYM_KeyRing        = "Mind Your Manors Key Ring"
Coast_KeyRing      = "Coast Key Ring"
Attic_KeyRing      = "Attic Key Ring"
Knight_KeyRing     = "Knight Key Ring"
Creepy2_KeyRing    = "Creepy 2 Key Ring"
Creepy3_KeyRing    = "Creepy 3 Key Ring"
Gusts1_KeyRing     = "Gusts 1 Key Ring"
Gusts2_KeyRing     = "Gusts 2 Key Ring"
DLD_KeyRing        = "Don't Look Down Key Ring"
Shiver_KeyRing     = "Shiver Key Ring"

Keys = "Keys"

#Warp Gates
Cellar4_Warp = "Cellar Warp"
Cliff4_Warp = "Cliff Warp"
Hedge4_Warp = "Hedge Warp"
Hedge6_Warp = "Greenhouse Warp"
Hedge9_Warp = "Hill Warp"
Fish3_Warp = "Dock Warp"
Fish7_Warp = "Fishy Clues Warp"
Balc1_Warp = "Cower Warp"
Balc4_Warp = "Attic Warp"
Balc6_Warp = "Knight Warp"
Grave1_Warp = "Graveplot Warp"
Grave5_Warp = "Crypt Warp"
Grave8_Warp = "Tomb Warp"
Manor3_Warp = "Clamor Warp"
Manor6_Warp = "MYM Warp"
LH14_Warp = "Coast Warp"
LH15_Warp = "Witch Way Warp"
LH18_Warp = "Lighthouse Warp"
SP3_Warp = "Creepy Warp"
SP5_Warp = "Gusts Warp"
Roof3_Warp = "Upstairs Warp"
SL2_Warp = "Lab Warp"
Wreck22_Warp = "Wreck Warp"
Wreck26_Warp = "Aghast Warp"
MG_Warp = "Monster Gallery Warp"

FillerSnack = "Spare Snack"

Warps = "Warps"

victory = "Victory"
